### ISSUE TITLE
Installing package should create "params" directory

### ISSUE THREAD

**Issue by borisindelman** [bouncingjack/twu#25]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\path\\to\\twu\\params\\params.json'

caused by not having the params directory

**Comment by bouncingjack** [comment]
Did you create the directory manually to be able to use the tool?

**Comment by borisindelman** [comment]
Yes. if I create the directory the install works fine.

**Comment by bouncingjack** [comment]
fixed in #27
